# Configuration file for JuliaFormatter.jl
# For more information, see: https://domluna.github.io/JuliaFormatter.jl/stable/config/

verbose = true
indent = 4
margin = 120
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = false
remove_extra_newlines = true
import_to_using = false
pipe_to_function_call = false
short_to_long_function_def = false
long_to_short_function_def = false
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = true
format_docstrings = true
conditional_to_if = false
normalize_line_endings = "auto"
trailing_comma = true
join_lines_based_on_source = true
indent_submodule = false
separate_kwargs_with_semicolon = false
surround_whereop_typeparameters = true
always_use_return = true
